TITLE = "Terrain Generation"
GAUSSIAN_MIXTURE_WEIGHT = 0.2
DOTS_PER_INCH = 300
IMAGE_DIR = "./data"
COLUMN_MORPHING = False
METHOD_OPTIONS = ["Evolution", "Morphing"]
PALETTE_OPTIONS = ["Storm", "Terrain", "Vincent"]
MODE_OPTIONS = ["Blending", "Mixture"]
MIXTURE_DISTRIBUTION_OPTIONS = ["Gaussian", "Uniform"]
BLENDING_DISTRIBUTION_OPTIONS = ["Gaussian", "Uniform"]
# AVERAGING_DISTRIBUTION_OPTIONS = ["periodic", "fixed"]
AVERAGING_OPTIONS = {
    'Periodic': 'periodic',
    'Fixed': 'fixed'}
DELTA_DEFAULT = 0.8
JUMP_DEFAULT = 0.5
NUM_FRAMES_DEFAULT = 10
START_SEED_DEFAULT = 134
END_SEED_DEFAULT = 143
EDGE_SIZE_OPTIONS = [32, 64, 128, 256, 512]
WIDTH_RESIZE_PERC = 54
VIDEO_FRAMES_PER_SEC = 5
